spring:
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:h2:mem:customers-db
  application:
    name: customer-service
  h2:
    console:
      enabled: true
  cloud:
    discovery:
      enabled: true
    config:
      enabled: false
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true