spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
    discovery:
      enabled: true
server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

