spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file://C:\Users\salah\Documents\micro_services\ecom-app-micro-services\config-repo
server:
  port: 9999
